import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import Navigation from "@/components/common/navigation/Navigation";
import Header from "@/components/common/header/Header";
import ImageGallery from "@/components/common/gallery/ImageGallery";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Header></Header>
        <Navigation></Navigation>
        {/* <ImageGallery></ImageGallery> */}
        {children}
      </body>
    </html>
  );
}
